"""Generates SF Pro pair-kerning tables for CupertinoUi from the fonts' GPOS data.

Every pair of the supported character set is shaped with HarfBuzz ("kern" on, ligatures off); the difference between the
shaped and the plain advance of the first glyph is the kerning value. Output: src/CupertinoUi/core/generated/KerningTables.inc
Usage: tools/.venv/Scripts/python.exe tools/fonts/kerning.py
"""

import os

import uharfbuzz as hb
from fontTools.ttLib import TTFont

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
FONTS = os.path.join(REPO, "reference", "fonts")
OUTPUT = os.path.join(REPO, "src", "CupertinoUi", "core", "generated", "KerningTables.inc")

FACES = [
    ("SfProTextRegular", "SF-Pro-Text-Regular.otf"),
    ("SfProTextMedium", "SF-Pro-Text-Medium.otf"),
    ("SfProTextSemibold", "SF-Pro-Text-Semibold.otf"),
    ("SfProTextBold", "SF-Pro-Text-Bold.otf"),
    ("SfProTextHeavy", "SF-Pro-Text-Heavy.otf"),
    ("SfProDisplayRegular", "SF-Pro-Display-Regular.otf"),
    ("SfProDisplayMedium", "SF-Pro-Display-Medium.otf"),
    ("SfProDisplaySemibold", "SF-Pro-Display-Semibold.otf"),
    ("SfProDisplayBold", "SF-Pro-Display-Bold.otf"),
]

RANGES = [(0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x2010, 0x2027), (0x2030, 0x203A), (0x20AC, 0x20AC), (0x2116, 0x2116), (0x400, 0x45F), (0x490, 0x491)]


def characters(font):
    cmap = font.getBestCmap()
    return [code for start, end in RANGES for code in range(start, end + 1) if code in cmap]


def shape_advances(hb_font, text):
    buffer = hb.Buffer()
    buffer.add_str(text)
    buffer.guess_segment_properties()
    hb.shape(hb_font, buffer, {"kern": True, "liga": False, "clig": False, "calt": False})
    return [position.x_advance for position in buffer.glyph_positions]


def kerning_pairs(path):
    font = TTFont(path, lazy=True)
    codes = characters(font)
    face = hb.Face(open(path, "rb").read())
    hb_font = hb.Font(face)
    base = {code: shape_advances(hb_font, chr(code))[0] for code in codes}
    pairs = []
    for left in codes:
        left_char = chr(left)
        for right in codes:
            advances = shape_advances(hb_font, left_char + chr(right))
            if len(advances) != 2:
                continue
            value = advances[0] - base[left]
            if value:
                pairs.append(((left << 16) | right, value))
    return font["head"].unitsPerEm, len(codes), pairs


def main():
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    lines = ["// Generated by tools/fonts/kerning.py from the SF Pro GPOS kerning; do not edit.", "// Each entry: (left codepoint << 16) | right codepoint, adjustment in font units (2048 per em).", ""]
    for name, file_name in FACES:
        units, count, pairs = kerning_pairs(os.path.join(FONTS, file_name))
        pairs.sort()
        lines.append(f"inline constexpr KerningPair {name}[] = {{")
        row = []
        for key, value in pairs:
            row.append(f"{{0x{key:08X}, {value}}}")
            if len(row) == 8:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("};")
        lines.append("")
        print(f"{name}: {count} characters, {len(pairs)} kerned pairs, {units} units per em")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


if __name__ == "__main__":
    main()
