"""Builds fonts with the layers of the SF Symbols that macOS draws in layers.

SF Pro keeps every symbol as one glyph; the layers of hierarchical and variable rendering (the level of a battery, the
arcs of Wi-Fi) are groups of its contours, in the same order in every scale and weight. This tool draws each layer of
the listed symbols as a glyph of its own with the symbol's advance, maps the layers of the small, medium and large
scales to private use codepoints of Plane 15, and writes the table the library draws them from.
Output: reference/fonts/derived/SF-Symbols-Layers-{Weight}.otf, src/CupertinoUi/core/generated/SymbolLayers.inc
Usage: tools/.venv/Scripts/python.exe tools/fonts/symbol_layers.py
"""

import os

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.t2CharStringPen import T2CharStringPen
from fontTools.ttLib import TTFont

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
FONTS = os.path.join(REPO, "reference", "fonts")
OUTPUT = os.path.join(FONTS, "derived")
TABLE = os.path.join(REPO, "src", "CupertinoUi", "core", "generated", "SymbolLayers.inc")
WEIGHTS = ["Regular", "Medium", "Semibold", "Bold", "Heavy"]
SCALES = ["small", "medium", "large"]
FIRST = 0xF0000

# A symbol's layers from the first to light up with a variable value to the last: the level of each (0 primary, 1
# secondary in hierarchical rendering) and the indices of its contours. A battery's level is primary, its outline and cap
# secondary (Bluetooth @2x); Wi-Fi lights its dot, then the inner and the outer arc (Wi-Fi @2x).
BATTERY = [(1, [0, 1, 3]), (0, [2])]
LAYERS = {
    0x100647: ("wifi", [(0, [2]), (0, [1]), (0, [0])]),
    0x1006EA: ("battery.0percent", [(1, [0, 1, 2])]),
    0x1006E9: ("battery.25percent", BATTERY),
    0x100EB6: ("battery.50percent", BATTERY),
    0x100EB8: ("battery.75percent", BATTERY),
    0x1006E8: ("battery.100percent", BATTERY),
}


def contours(glyph_set, name):
    """The glyph's contours as lists of pen calls."""
    recording = RecordingPen()
    glyph_set[name].draw(recording)
    result, current = [], []
    for operator, operands in recording.value:
        current.append((operator, operands))
        if operator in ("closePath", "endPath"):
            result.append(current)
            current = []
    return result


def draw_layer(parts, width):
    pen, bounds = T2CharStringPen(width, None), BoundsPen(None)
    for part in parts:
        for operator, operands in part:
            getattr(pen, operator)(*operands)
            getattr(bounds, operator)(*operands)
    left = bounds.bounds[0] if bounds.bounds else 0
    return pen.getCharString(), (width, int(round(left)))


def build(weight):
    source = TTFont(os.path.join(FONTS, f"SF-Pro-Text-{weight}.otf"))
    cmap, glyph_set, hmtx = source.getBestCmap(), source.getGlyphSet(), source["hmtx"]
    notdef = T2CharStringPen(0, None)
    order, char_strings, metrics, mapping = [".notdef"], {".notdef": notdef.getCharString()}, {".notdef": (0, 0)}, {}
    rows = []
    code = FIRST
    for symbol, (name, layers) in LAYERS.items():
        rows.append((symbol, name, code, layers))
        base = cmap[symbol].rsplit(".", 1)[0]
        for scale in SCALES:
            glyph = f"{base}.{scale}"
            parts = contours(glyph_set, glyph)
            for index, (_, indices) in enumerate(layers):
                layer = f"{name}.{scale}.{index}"
                char_strings[layer], metrics[layer] = draw_layer([parts[i] for i in indices], hmtx[glyph][0])
                order.append(layer)
                mapping[code] = layer
                code += 1

    hhea, os2 = source["hhea"], source["OS/2"]
    builder = FontBuilder(source["head"].unitsPerEm, isTTF=False)
    builder.setupGlyphOrder(order)
    builder.setupCharacterMap(mapping)
    builder.setupCFF(f"SFSymbolsLayers-{weight}", {"FullName": f"SF Symbols Layers {weight}"}, char_strings, {})
    builder.setupHorizontalMetrics(metrics)
    builder.setupHorizontalHeader(ascent=hhea.ascent, descent=hhea.descent, lineGap=hhea.lineGap)
    builder.setupNameTable({"familyName": "SF Symbols Layers", "styleName": weight})
    builder.setupOS2(sTypoAscender=os2.sTypoAscender, sTypoDescender=os2.sTypoDescender, sTypoLineGap=os2.sTypoLineGap, usWinAscent=os2.usWinAscent, usWinDescent=os2.usWinDescent)
    builder.setupPost()
    path = os.path.join(OUTPUT, f"SF-Symbols-Layers-{weight}.otf")
    builder.save(path)
    return path, rows


def write_table(rows):
    lines = [
        "// Generated by tools/fonts/symbol_layers.py: the symbols drawn in layers, the codepoint of their first layer in the",
        "// layer fonts (the small, medium and large scales follow each other), the number of layers and the level of each",
        "// (0 primary, 1 secondary) from the first to light up to the last.",
    ]
    for symbol, name, code, layers in rows:
        levels = ", ".join(str(level) for level, _ in layers)
        lines.append(f"{{0x{symbol:06X}, 0x{code:05X}, {len(layers)}, {{{levels}}}}}, // {name}")
    with open(TABLE, "w", encoding="utf-8", newline="\n") as table:
        table.write("\n".join(lines) + "\n")


def main():
    os.makedirs(OUTPUT, exist_ok=True)
    for weight in WEIGHTS:
        path, rows = build(weight)
        print(f"{len(rows)} symbols -> {os.path.relpath(path, REPO)} ({os.path.getsize(path) // 1024} KB)")
    write_table(rows)
    print("table ->", os.path.relpath(TABLE, REPO))


if __name__ == "__main__":
    main()
